In [43]:
import numpy as np
import scipy.linalg as la

In [55]:
# Make least squares equation objects
epsilon = 10**(-9)
first_column = np.array([[1.],[1.],[1.]])
second_column = np.array([[1 + epsilon],[1.],[1.]])
A = np.concatenate((first_column, second_column), axis = 1)
b = first_column
display(A, b)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[1.],
       [1.],
       [1.]])

We have $A = \begin{bmatrix} 1 & 1 + \epsilon\\ 1 & 1\\ 1 & 1 \end{bmatrix},  b = \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}.$  The least squares solution to $Ax \approx b$ should minimize the distance between $Ax$ and $b$.  
Observe that $b \in R(A)$ and so the least squares solution is $x = \begin{bmatrix} 1 \\ 0 \end{bmatrix}$ to give the perfect fit $Ax = \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix} = b$.

In [56]:
# Solve directly from least squares equation 

x = np.linalg.inv(A.T@A)@A.T@b
print('x* = ') 
print(x)
print('')
print('Ax* = ')
print(A@x)

LinAlgError: Singular matrix

In [54]:
# Solve using QR decomposition

Q1, R1 = la.qr(A, mode = 'economic')

x = np.linalg.inv(R1)@Q1.T@b
print('x* = ')
print(x)
print('')
print('Ax* = ')
print(A@x)

x* = 
[[1.]
 [0.]]

Ax* = 
[[1.]
 [1.]
 [1.]]
